import type { Metadata } from "next";
import "./globals.css";
import "@fontsource-variable/lora/wght.css";
import "@fontsource-variable/merriweather/wght.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`} data-theme="dark">
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
